const databaseOpere = {
    'orfeo': {
        file: 'orfeo',
        autore: 'Antonio Canova',
        dateAutore: 'Possagno, 1757 - Venezia, 1822',
        titolo: 'Orfeo ed Euridice',
        titoloEn: 'Orpheus and Eurydice',
        anno: '1773 - 1775',
        tecnica: 'Marmo su basamento / <span>Marble</span>',
        testo: `<p>L'istante fatale del volgersi: quando l'amore sfida l'abisso e perde.</p>`,
        poesia: `"Un solo sguardo indietro,<br>e l'ombra si riprese il fiore."`,
        traccia: 'ABYSS',
        artista: 'ARTISTA SCONOSCIUTO',
        recensione: `La sindrome dell'overthinking resa marmo. Il dubbio che distrugge tutto a un passo dal traguardo.`,
        testoCanzone: `(Strumentale / Testo non disponibile)`
    },
    'ercole': {
        file: 'ercole',
        autore: 'Antonio Canova',
        dateAutore: 'Possagno, 1757 - Venezia, 1822',
        titolo: 'Ercole e Lica',
        titoloEn: 'Hercules and Lichas',
        anno: '1795 - 1815',
        tecnica: 'Marmo su basamento / <span>Marble</span>',
        testo: `<p>La forma massima del dolore fisico e della furia che precede l'inevitabile.</p>`,
        poesia: `"La forza si fa cieca,<br>il cielo trema al grido dell'eroe spezzato."`,
        traccia: 'FURY',
        artista: 'ARTISTA SCONOSCIUTO',
        recensione: `La rabbia tossica e la perdita di controllo. Un'esplosione di energia cinetica imprigionata nella staticità della pietra.`,
        testoCanzone: `(Strumentale / Testo non disponibile)`
    },
    'giacente': {
        file: 'giacente',
        autore: 'Antonio Canova',
        dateAutore: 'Possagno, 1757 - Venezia, 1822',
        titolo: 'Maddalena Giacente',
        titoloEn: 'Recumbent Magdalene',
        anno: '1819 - 1822',
        tecnica: 'Marmo su basamento / <span>Marble</span>',
        testo: `<p>Un abbandono marmoreo tra l'ultimo respiro e l'eternità.</p>`,
        poesia: `Forse perchè della fatal quïete<br>Tu sei l’immago... (Ugo Foscolo)`,
        traccia: 'FADE OUT',
        artista: 'ARTISTA SCONOSCIUTO',
        recensione: `L'accettazione finale. Quando si smette di combattere e ci si lascia andare alla stasi totale.`,
        testoCanzone: `(Strumentale / Testo non disponibile)`
    },
    'penitente': {
        file: 'penitente',
        autore: 'Antonio Canova',
        dateAutore: 'Possagno, 1757 - Venezia, 1822',
        titolo: 'Maddalena Penitente',
        titoloEn: 'Penitent Magdalene',
        anno: '1793 - 1796',
        tecnica: 'Marmo su basamento / <span>Marble</span>',
        testo: `<p>La bellezza che si consuma nel pensiero dell'oltre, tra colpa e redenzione.</p>`,
        poesia: `"Una croce stretta al petto scarno<br>le lacrime invisibili solcano la pietra."`,
        traccia: 'REPENTANCE',
        artista: 'ARTISTA SCONOSCIUTO',
        recensione: `Il senso di colpa come forza autodistruttiva.`,
        testoCanzone: `(Strumentale / Testo non disponibile)`
    },
    'amore_psiche': {
        file: 'amore_psiche',
        autore: 'Antonio Canova',
        dateAutore: 'Possagno, 1757 - Venezia, 1822',
        titolo: 'Amore e Psiche',
        titoloEn: 'Psyche Revived by Cupid\'s Kiss',
        anno: '1787 - 1793',
        tecnica: 'Marmo su basamento / <span>Marble</span>',
        testo: `<p>Il momento esatto in cui l'amore risveglia l'anima, strappandola al sonno della morte.</p>`,
        poesia: `"Un soffio leggero sul volto di marmo<br>e la morte si arrende al bacio eterno."`,
        traccia: 'AWAKE',
        artista: 'ARTISTA SCONOSCIUTO',
        recensione: `Un pezzo che esplora la connessione tra mente e desiderio.`,
        testoCanzone: `(Strumentale / Testo non disponibile)`
    },
    'perseo': {
        file: 'perseo',
        autore: 'Antonio Canova',
        dateAutore: 'Possagno, 1757 - Venezia, 1822',
        titolo: 'Perseo Trionfante',
        titoloEn: 'Triumphant Perseus',
        anno: '1797 - 1801',
        tecnica: 'Marmo su basamento / <span>Marble</span>',
        testo: `<p>Perseo con la testa di Medusa. Un giovane eroe che ha appena sconfitto il mostro...</p>`,
        poesia: `"Dormi, o mostro, che il mio braccio ha domato."`,
        traccia: 'BELIEVER',
        artista: 'IMAGINE DRAGONS',
        recensione: `Un'opera che spacca i canoni. Il problem-solving sotto stress.`,
        testoCanzone: `First things first...`
    }
};